/********************************************************************
**                      SHOWBMP Header File                        **
********************************************************************/

#define ID_MAINWIN         1

#define IDD_ABOUT          50
#define IDD_OPEN           51

#define IDM_FILE           100
#define IDM_FILE_NEW       101
#define IDM_FILE_OPEN      102
#define IDM_FILE_SAVE      103
#define IDM_FILE_SAVEAS    104
#define IDM_FILE_INFO      105
#define IDM_FILE_ABOUT     106
#define IDM_FILE_EXIT      107


#define IDM_HELP           199

#define IDS_ERROR01        200
#define IDS_ERROR02        201
#define IDS_ERROR03        202
#define IDS_ERROR04        203
#define IDS_ERROR05        204
#define IDS_ERROR06        205

#define IDS_TITLE          260
#define IDS_ERROR          261
#define IDS_DEBUG          262
#define IDS_VIEWINFO       263
#define IDS_UNTITLED       264
#define IDS_WORKING        265

#define IDS_FORMAT01       270
#define IDS_FORMAT02       271
#define IDS_FORMAT03       272
#define IDS_FORMAT04       273

#define IDD_PATH           300
#define IDD_FILEEDIT       301
#define IDD_DEVLIST        302
#define IDD_DIRLIST        303
#define IDD_FILELIST       304

#define UWM_BITMAP_READY   (WM_USER+0)     // Bitmap ready msg
#define UWM_BITMAP_ERROR   (WM_USER+1)     // Bitmap error msg
